### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Zombieland4942** [shanemadden/factorio-deadlock-crating#14]
Hey @shanemadden,

Thanks for merging the change. Just letting you know the mod is still marked as deprecated in the mod portal, and discussions are disabled, just thought I would mention it just in case.

**Comment by shanemadden** [comment]
Deadlock made the decision to disable discussion on the mod, due to harassment he was getting related to Industrial Revolution - I don't want people to start using that as an avenue to light up his inbox again. :( I noticed that the mod portal search still shows it, but it seems that it pretty much makes it not installable in-game to have it marked as deprecated, so I should probably remove that flag, I think?

**Comment by Zombieland4942** [comment]
Thats a shame regarding Deadlock... Changing it from deprecated would be nice, and if it breaks in the future and no one is keen to sink time into it again, then it could just be marked as deprecated again.

**Comment by shanemadden** [comment]
All set! Thanks :)
