### ISSUE TITLE
Feature Suggestion: Hide Crating Recipies

### ISSUE THREAD

**Issue by ghost** [shanemadden/factorio-deadlock-crating#20]
Add an option to "Remove crating recipies from the player crafting tab." similar to Deadlock's Stacking Beltboxes and Compact Loaders option to "Hide Unstacking Recipes".

This should hide the entire crating tab, providing less clutter for those who already have many mods - and the usefulness of handcrafting crates is somewhat debatable anyways.

**Comment by qqllwllpp** [comment]
I Tried to implement it but this is not possible due to way Crating Machines are setup: they are assemblers in game logic and require configuration of recipes. Possibility to hide recipes only exist for recipes for furnaces(the building capable to detect which resources are placed in it) and it is possible to create such recipe only with single input. The crating process requires ate least two: resource + container.

**Comment by ghost** [comment]
Thanks for trying, closing.
